spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/kassinimvp
  application:
    name: chat-service

service:
  api:
    version: 0.0.1
  organization:
    name: Kassini MVP
  security:
    secret: LgFRkEdNkP4dUFYxlc4aT4J2rZ8JeEf9wNpC0gU2Qcw9LRM4kgVcvNvUTcv6rhPw
    expirationMS: 3600000 # token expires in 1hr after issuing
server:
  port: 9101