spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/hobbyz_hub_database
  application:
    name: chat-service

service:
  api:
    version: 0.0.1
  organization:
    name: Tropic World Paradise
  security:
    secret: sampleSecret
    expirationMS: 3600 # token expires in 1hr after issuing
server:
  port: 9101